const videoAudio = {
  subreddit: "Overwatch",
  selftext: "",
  saved: false,
  title: "An open video letter to Moiras from a McCree main",
  link_flair_richtext: [{ e: "text", t: "Humor" }],
  subreddit_name_prefixed: "r/Overwatch",
  hidden: false,
  thumbnail_height: 78,
  parent_whitelist_status: "all_ads",
  hide_score: false,
  name: "t3_ci826i",
  quarantine: false,
  link_flair_text_color: "dark",
  upvote_ratio: 0.95,
  author_flair_background_color: null,
  subreddit_type: "public",
  ups: 13241,
  total_awards_received: 12,
  media_embed: {},
  thumbnail_width: 140,
  author_flair_template_id: "5d2d9a4e-9bba-11e9-82f6-0e6a08544ee4",
  is_original_content: false,
  author_fullname: "t2_i2257",
  secure_media: {
    reddit_video: {
      fallback_url: "https://v.redd.it/ga1ywiqzhpc31/DASH_720?source=fallback",
      height: 720,
      width: 1280,
      scrubber_media_url: "https://v.redd.it/ga1ywiqzhpc31/DASH_96",
      dash_url: "https://v.redd.it/ga1ywiqzhpc31/DASHPlaylist.mpd",
      duration: 38,
      hls_url: "https://v.redd.it/ga1ywiqzhpc31/HLSPlaylist.m3u8",
      is_gif: false,
      transcoding_status: "completed",
    },
  },
  is_reddit_media_domain: true,
  is_meta: false,
  category: null,
  num_comments: 379,
  secure_media_embed: {},
  link_flair_text: "Humor",
  can_mod_post: false,
  num_duplicates: 1,
  approved_by: null,
  thumbnail:
    "https://b.thumbs.redditmedia.com/fn-8pI3VFBUX1mRGTwiNcXD17-QC628YxyI6QyU1PNc.jpg",
  edited: false,
  author_flair_css_class: "S03 C00 R09",
  author_flair_richtext: [{ e: "text", t: "Let’s dance, ghost." }],
  gildings: { gid_1: 9, gid_2: 2, gid_3: 1 },
  post_hint: "hosted:video",
  content_categories: ["gaming"],
  is_self: false,
  mod_note: null,
  created: 1564201789,
  link_flair_type: "richtext",
  wls: 6,
  banned_by: null,
  author_flair_type: "richtext",
  domain: "v.redd.it",
  allow_live_comments: true,
  selftext_html: null,
  likes: null,
  suggested_sort: null,
  banned_at_utc: null,
  view_count: null,
  archived: false,
  score: 13241,
  no_follow: false,
  is_crosspostable: true,
  pinned: false,
  over_18: false,
  preview: {
    images: [
      {
        source: {
          url:
            "https://external-preview.redd.it/UPE0hIJDMmZ_lHDZdmMHCDDEAqLcyT-CoaNsUvu4u50.png?format=pjpg&auto=webp&s=9c0f1880e548b383a73189606e0bfef05c80d573",
          width: 1280,
          height: 720,
        },
        resolutions: [
          {
            url:
              "https://external-preview.redd.it/UPE0hIJDMmZ_lHDZdmMHCDDEAqLcyT-CoaNsUvu4u50.png?width=108&crop=smart&format=pjpg&auto=webp&s=651e2c1812dfea634e22dc2f33b5fa5c06aac1e2",
            width: 108,
            height: 60,
          },
          {
            url:
              "https://external-preview.redd.it/UPE0hIJDMmZ_lHDZdmMHCDDEAqLcyT-CoaNsUvu4u50.png?width=216&crop=smart&format=pjpg&auto=webp&s=5b30bdf6f8c5d4d1dcac35371c8a68c12e094574",
            width: 216,
            height: 121,
          },
          {
            url:
              "https://external-preview.redd.it/UPE0hIJDMmZ_lHDZdmMHCDDEAqLcyT-CoaNsUvu4u50.png?width=320&crop=smart&format=pjpg&auto=webp&s=695fc0f2a24c944b15982dfa73b5ccc4b11c5136",
            width: 320,
            height: 180,
          },
          {
            url:
              "https://external-preview.redd.it/UPE0hIJDMmZ_lHDZdmMHCDDEAqLcyT-CoaNsUvu4u50.png?width=640&crop=smart&format=pjpg&auto=webp&s=975c840702fee185828c79fe86adaa14f47f6f53",
            width: 640,
            height: 360,
          },
          {
            url:
              "https://external-preview.redd.it/UPE0hIJDMmZ_lHDZdmMHCDDEAqLcyT-CoaNsUvu4u50.png?width=960&crop=smart&format=pjpg&auto=webp&s=1c3ac7a67389ed72a0933577d224f74ad2433485",
            width: 960,
            height: 540,
          },
          {
            url:
              "https://external-preview.redd.it/UPE0hIJDMmZ_lHDZdmMHCDDEAqLcyT-CoaNsUvu4u50.png?width=1080&crop=smart&format=pjpg&auto=webp&s=eb7b79946f9b9e5762324d79487731af034f8131",
            width: 1080,
            height: 607,
          },
        ],
        variants: {},
        id: "tDJ7F7Q2Psn68nUj0h1KU-tKBrmejIRMFkCuXRCnIGw",
      },
    ],
    enabled: false,
  },
  media_only: false,
  link_flair_template_id: "2c6460c0-1e48-11e6-a119-0ee4e0cb4e81",
  can_gild: true,
  spoiler: false,
  locked: false,
  author_flair_text: "Let’s dance, ghost.",
  visited: false,
  num_reports: null,
  distinguished: null,
  subreddit_id: "t5_2u5kl",
  mod_reason_by: null,
  removal_reason: null,
  link_flair_background_color: "",
  id: "ci826i",
  is_robot_indexable: true,
  report_reasons: null,
  author: "Deadlibor",
  num_crossposts: 1,
  media: {
    reddit_video: {
      fallback_url: "https://v.redd.it/ga1ywiqzhpc31/DASH_720?source=fallback",
      height: 720,
      width: 1280,
      scrubber_media_url: "https://v.redd.it/ga1ywiqzhpc31/DASH_96",
      dash_url: "https://v.redd.it/ga1ywiqzhpc31/DASHPlaylist.mpd",
      duration: 38,
      hls_url: "https://v.redd.it/ga1ywiqzhpc31/HLSPlaylist.m3u8",
      is_gif: false,
      transcoding_status: "completed",
    },
  },
  send_replies: true,
  contest_mode: false,
  author_patreon_flair: false,
  author_flair_text_color: "dark",
  permalink:
    "/r/Overwatch/comments/ci826i/an_open_video_letter_to_moiras_from_a_mccree_main/",
  whitelist_status: "all_ads",
  stickied: false,
  url: "https://v.redd.it/ga1ywiqzhpc31",
  subreddit_subscribers: 2452111,
  created_utc: 1564172989,
  discussion_type: null,
  mod_reports: [],
  is_video: true,
};

const videoIsGif = {
  _fetch: null,
  _hasFetched: true,
  approved_at_utc: null,
  subreddit: { display_name: "aww" },
  selftext: "",
  user_reports: [],
  saved: false,
  mod_reason_title: null,
  gilded: 0,
  clicked: false,
  title: "How blackholes are discovered",
  link_flair_richtext: [],
  subreddit_name_prefixed: "r/aww",
  hidden: false,
  pwls: 6,
  link_flair_css_class: null,
  downs: 0,
  thumbnail_height: 140,
  parent_whitelist_status: "all_ads",
  hide_score: false,
  name: "t3_co137a",
  quarantine: false,
  link_flair_text_color: "dark",
  upvote_ratio: 0.97,
  author_flair_background_color: null,
  subreddit_type: "public",
  ups: 40008,
  total_awards_received: 1,
  media_embed: {},
  thumbnail_width: 140,
  author_flair_template_id: null,
  is_original_content: false,
  author_fullname: "t2_qz120",
  secure_media: {
    reddit_video: {
      fallback_url: "https://v.redd.it/fhkm7yfzref31/DASH_1080?source=fallback",
      height: 1080,
      width: 1080,
      scrubber_media_url: "https://v.redd.it/fhkm7yfzref31/DASH_96",
      dash_url: "https://v.redd.it/fhkm7yfzref31/DASHPlaylist.mpd",
      duration: 10,
      hls_url: "https://v.redd.it/fhkm7yfzref31/HLSPlaylist.m3u8",
      is_gif: true,
      transcoding_status: "completed",
    },
  },
  is_reddit_media_domain: true,
  is_meta: false,
  category: null,
  num_comments: 317,
  secure_media_embed: {},
  link_flair_text: null,
  can_mod_post: false,
  num_duplicates: 7,
  approved_by: null,
  thumbnail:
    "https://b.thumbs.redditmedia.com/4UZtuHc9Lg6jk98y4Hpq56aHXbENvOyOQkwRwtqR0NU.jpg",
  edited: false,
  author_flair_css_class: null,
  author_flair_richtext: [],
  gildings: { gid_1: 1 },
  post_hint: "hosted:video",
  content_categories: null,
  is_self: false,
  mod_note: null,
  created: 1565378994,
  link_flair_type: "text",
  wls: 6,
  banned_by: null,
  author_flair_type: "text",
  domain: "v.redd.it",
  allow_live_comments: true,
  selftext_html: null,
  likes: null,
  suggested_sort: null,
  banned_at_utc: null,
  view_count: null,
  archived: false,
  score: 40008,
  no_follow: false,
  is_crosspostable: true,
  pinned: false,
  over_18: false,
  preview: {
    images: [
      {
        source: {
          url:
            "https://external-preview.redd.it/nT8Ku2wLjyPzNNEsq2B-8ipfwXw4oSTUDIA9ACrNhF4.png?format=pjpg&auto=webp&s=0f0d0b4f00b71e61b8daa0044401d18efb506bdf",
          width: 1080,
          height: 1080,
        },
        resolutions: [
          {
            url:
              "https://external-preview.redd.it/nT8Ku2wLjyPzNNEsq2B-8ipfwXw4oSTUDIA9ACrNhF4.png?width=108&crop=smart&format=pjpg&auto=webp&s=04b37fa6529406dd5870fbb9bee8b23c9f3c102d",
            width: 108,
            height: 108,
          },
          {
            url:
              "https://external-preview.redd.it/nT8Ku2wLjyPzNNEsq2B-8ipfwXw4oSTUDIA9ACrNhF4.png?width=216&crop=smart&format=pjpg&auto=webp&s=f8f4e86d2aaf846ad27cda2dd1ce013121d2cc7b",
            width: 216,
            height: 216,
          },
          {
            url:
              "https://external-preview.redd.it/nT8Ku2wLjyPzNNEsq2B-8ipfwXw4oSTUDIA9ACrNhF4.png?width=320&crop=smart&format=pjpg&auto=webp&s=ccb557dfd02cc4d665e7c16f34e84449fdd5d6db",
            width: 320,
            height: 320,
          },
          {
            url:
              "https://external-preview.redd.it/nT8Ku2wLjyPzNNEsq2B-8ipfwXw4oSTUDIA9ACrNhF4.png?width=640&crop=smart&format=pjpg&auto=webp&s=52a5e3d90c6e2d67e5ab4c1dc8451b889eb60457",
            width: 640,
            height: 640,
          },
          {
            url:
              "https://external-preview.redd.it/nT8Ku2wLjyPzNNEsq2B-8ipfwXw4oSTUDIA9ACrNhF4.png?width=960&crop=smart&format=pjpg&auto=webp&s=c9848492c105f9efc8c38b20c6e06551e4250735",
            width: 960,
            height: 960,
          },
          {
            url:
              "https://external-preview.redd.it/nT8Ku2wLjyPzNNEsq2B-8ipfwXw4oSTUDIA9ACrNhF4.png?width=1080&crop=smart&format=pjpg&auto=webp&s=38e152b2ed444bac7d48f53bd1975e4d42689f4b",
            width: 1080,
            height: 1080,
          },
        ],
        variants: {},
        id: "Q3G6Z2xPOKu7LccYIIBzzndODrhivuQdy6gWiq7FP1E",
      },
    ],
    enabled: false,
  },
  all_awardings: [
    {
      is_enabled: true,
      count: 1,
      subreddit_id: null,
      description: "Shows the Silver Award... and that's it.",
      name: "Silver",
      icon_width: 512,
      icon_url: "https://www.redditstatic.com/gold/awards/icon/silver_512.png",
      days_of_premium: 0,
      subreddit_coin_reward: 0,
      icon_height: 512,
      resized_icons: [
        {
          url: "https://www.redditstatic.com/gold/awards/icon/silver_16.png",
          width: 16,
          height: 16,
        },
        {
          url: "https://www.redditstatic.com/gold/awards/icon/silver_32.png",
          width: 32,
          height: 32,
        },
        {
          url: "https://www.redditstatic.com/gold/awards/icon/silver_48.png",
          width: 48,
          height: 48,
        },
        {
          url: "https://www.redditstatic.com/gold/awards/icon/silver_64.png",
          width: 64,
          height: 64,
        },
        {
          url: "https://www.redditstatic.com/gold/awards/icon/silver_128.png",
          width: 128,
          height: 128,
        },
      ],
      days_of_drip_extension: 0,
      award_type: "global",
      coin_price: 100,
      id: "gid_1",
      coin_reward: 0,
    },
  ],
  media_only: false,
  can_gild: true,
  spoiler: false,
  locked: false,
  author_flair_text: null,
  visited: false,
  num_reports: null,
  distinguished: null,
  subreddit_id: "t5_2qh1o",
  mod_reason_by: null,
  removal_reason: null,
  link_flair_background_color: "",
  id: "co137a",
  is_robot_indexable: true,
  report_reasons: null,
  author: { name: "Bloody-August" },
  num_crossposts: 10,
  media: {
    reddit_video: {
      fallback_url: "https://v.redd.it/fhkm7yfzref31/DASH_1080?source=fallback",
      height: 1080,
      width: 1080,
      scrubber_media_url: "https://v.redd.it/fhkm7yfzref31/DASH_96",
      dash_url: "https://v.redd.it/fhkm7yfzref31/DASHPlaylist.mpd",
      duration: 10,
      hls_url: "https://v.redd.it/fhkm7yfzref31/HLSPlaylist.m3u8",
      is_gif: true,
      transcoding_status: "completed",
    },
  },
  send_replies: true,
  contest_mode: false,
  author_patreon_flair: false,
  author_flair_text_color: null,
  permalink: "/r/aww/comments/co137a/how_blackholes_are_discovered/",
  whitelist_status: "all_ads",
  stickied: false,
  url: "https://v.redd.it/fhkm7yfzref31",
  subreddit_subscribers: 21500279,
  created_utc: 1565350194,
  discussion_type: null,
  mod_reports: [],
  is_video: true,
  comments: [],
};

const tweet = {
  approved_at_utc: null,
  subreddit: "SandersForPresident",
  selftext: "",
  user_reports: [],
  saved: false,
  mod_reason_title: null,
  gilded: 0,
  clicked: false,
  title:
    'Mike Gravel: "I am proud and honored to endorse Senator Bernie Sanders for the presidency of the United States."',
  link_flair_richtext: [],
  subreddit_name_prefixed: "r/SandersForPresident",
  hidden: false,
  pwls: 6,
  link_flair_css_class: null,
  downs: 0,
  thumbnail_height: 78,
  parent_whitelist_status: "all_ads",
  hide_score: false,
  name: "t3_cmr0sw",
  quarantine: false,
  link_flair_text_color: "dark",
  upvote_ratio: 0.92,
  author_flair_background_color: "",
  subreddit_type: "public",
  ups: 7950,
  total_awards_received: 0,
  media_embed: {
    content:
      '<blockquote class="twitter-video"><p lang="en" dir="ltr">&quot;I am proud and honored to endorse Senator Bernie Sanders for the presidency of the United States.&quot; <a href="https://t.co/Y7uf8ebbhD">pic.twitter.com/Y7uf8ebbhD</a></p>&mdash; Mike Gravel (@MikeGravel) <a href="https://twitter.com/MikeGravel/status/1158739504829779969?ref_src=twsrc%5Etfw">August 6, 2019</a></blockquote>\n<script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>\n',
    width: 350,
    scrolling: false,
    height: 200,
  },
  thumbnail_width: 140,
  author_flair_template_id: null,
  is_original_content: false,
  author_fullname: "t2_6n9wb",
  secure_media: {
    type: "twitter.com",
    oembed: {
      provider_url: "https://twitter.com",
      version: "1.0",
      url: "https://twitter.com/MikeGravel/status/1158739504829779969",
      author_name: "Mike Gravel",
      height: null,
      width: 350,
      html:
        '<blockquote class="twitter-video"><p lang="en" dir="ltr">&quot;I am proud and honored to endorse Senator Bernie Sanders for the presidency of the United States.&quot; <a href="https://t.co/Y7uf8ebbhD">pic.twitter.com/Y7uf8ebbhD</a></p>&mdash; Mike Gravel (@MikeGravel) <a href="https://twitter.com/MikeGravel/status/1158739504829779969?ref_src=twsrc%5Etfw">August 6, 2019</a></blockquote>\n<script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>\n',
      author_url: "https://twitter.com/MikeGravel",
      provider_name: "Twitter",
      cache_age: 3153600000,
      type: "rich",
    },
  },
  is_reddit_media_domain: false,
  is_meta: false,
  category: null,
  num_comments: 236,
  secure_media_embed: {
    content:
      '<blockquote class="twitter-video"><p lang="en" dir="ltr">&quot;I am proud and honored to endorse Senator Bernie Sanders for the presidency of the United States.&quot; <a href="https://t.co/Y7uf8ebbhD">pic.twitter.com/Y7uf8ebbhD</a></p>&mdash; Mike Gravel (@MikeGravel) <a href="https://twitter.com/MikeGravel/status/1158739504829779969?ref_src=twsrc%5Etfw">August 6, 2019</a></blockquote>\n<script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>\n',
    width: 350,
    scrolling: false,
    media_domain_url: "https://www.redditmedia.com/mediaembed/cmr0sw",
    height: 200,
  },
  link_flair_text: null,
  can_mod_post: false,
  num_duplicates: 5,
  approved_by: null,
  thumbnail:
    "https://b.thumbs.redditmedia.com/FhjQ4-j5JZt-ZORrmRldIm0O7HK4gZMUJd42igNZ-Oc.jpg",
  edited: false,
  author_flair_css_class: "SGP",
  author_flair_richtext: [{ e: "text", t: "American Values - 🐦 🎒" }],
  gildings: {},
  post_hint: "link",
  content_categories: null,
  is_self: false,
  mod_note: null,
  created: 1565129192,
  link_flair_type: "text",
  wls: 6,
  banned_by: null,
  author_flair_type: "richtext",
  domain: "twitter.com",
  allow_live_comments: false,
  selftext_html: null,
  likes: null,
  suggested_sort: "confidence",
  banned_at_utc: null,
  view_count: null,
  archived: false,
  score: 7950,
  no_follow: false,
  is_crosspostable: true,
  pinned: false,
  over_18: false,
  preview: {
    images: [
      {
        source: {
          url:
            "https://external-preview.redd.it/ooJ9Wcue6reQGbbMLWyGWp4Sa1a3S1PGGvNV3cr0res.jpg?auto=webp&s=bae9b6a11ef9af28ddac53bf842a3b41da84814e",
          width: 140,
          height: 78,
        },
        resolutions: [
          {
            url:
              "https://external-preview.redd.it/ooJ9Wcue6reQGbbMLWyGWp4Sa1a3S1PGGvNV3cr0res.jpg?width=108&crop=smart&auto=webp&s=d930ab691560d4e7922c2277290028467eb980a5",
            width: 108,
            height: 60,
          },
        ],
        variants: {},
        id: "z13tjB3eGEm7fwCk7O8rBpi9Ai0nGN7KRUoWBcDHsBI",
      },
    ],
    enabled: false,
  },
  all_awardings: [],
  media_only: false,
  can_gild: true,
  spoiler: false,
  locked: false,
  author_flair_text: "American Values - 🐦 🎒",
  visited: false,
  num_reports: null,
  distinguished: null,
  subreddit_id: "t5_2zbq7",
  mod_reason_by: null,
  removal_reason: null,
  link_flair_background_color: "",
  id: "cmr0sw",
  is_robot_indexable: true,
  report_reasons: null,
  author: "kevinmrr",
  num_crossposts: 0,
  media: {
    type: "twitter.com",
    oembed: {
      provider_url: "https://twitter.com",
      version: "1.0",
      url: "https://twitter.com/MikeGravel/status/1158739504829779969",
      author_name: "Mike Gravel",
      height: null,
      width: 350,
      html:
        '<blockquote class="twitter-video"><p lang="en" dir="ltr">&quot;I am proud and honored to endorse Senator Bernie Sanders for the presidency of the United States.&quot; <a href="https://t.co/Y7uf8ebbhD">pic.twitter.com/Y7uf8ebbhD</a></p>&mdash; Mike Gravel (@MikeGravel) <a href="https://twitter.com/MikeGravel/status/1158739504829779969?ref_src=twsrc%5Etfw">August 6, 2019</a></blockquote>\n<script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>\n',
      author_url: "https://twitter.com/MikeGravel",
      provider_name: "Twitter",
      cache_age: 3153600000,
      type: "rich",
    },
  },
  send_replies: true,
  contest_mode: false,
  author_patreon_flair: false,
  author_flair_text_color: "dark",
  permalink:
    "/r/SandersForPresident/comments/cmr0sw/mike_gravel_i_am_proud_and_honored_to_endorse/",
  whitelist_status: "all_ads",
  stickied: false,
  url: "https://twitter.com/MikeGravel/status/1158739504829779969",
  subreddit_subscribers: 276593,
  created_utc: 1565100392,
  discussion_type: null,
  mod_reports: [],
  is_video: false,
};

const videoNoAudio = {
  approved_at_utc: null,
  subreddit: { display_name: "WatchPeopleDieInside" },
  selftext: "",
  author_fullname: "t2_1jcwjxt6",
  saved: false,
  mod_reason_title: null,
  gilded: 0,
  clicked: false,
  title: "There'a a girl in this party shocked by this dudes skill!",
  link_flair_richtext: [],
  subreddit_name_prefixed: "r/WatchPeopleDieInside",
  hidden: false,
  pwls: 6,
  link_flair_css_class: null,
  downs: 0,
  thumbnail_height: 140,
  hide_score: false,
  name: "t3_cx20x5",
  quarantine: false,
  link_flair_text_color: "dark",
  author_flair_background_color: null,
  subreddit_type: "public",
  ups: 27232,
  total_awards_received: 0,
  media_embed: {},
  thumbnail_width: 140,
  author_flair_template_id: null,
  is_original_content: false,
  user_reports: [],
  secure_media: {
    reddit_video: {
      fallback_url: "https://v.redd.it/9bo4r6mgjej31/DASH_480?source=fallback",
      height: 480,
      width: 270,
      scrubber_media_url: "https://v.redd.it/9bo4r6mgjej31/DASH_96",
      dash_url: "https://v.redd.it/9bo4r6mgjej31/DASHPlaylist.mpd",
      duration: 19,
      hls_url: "https://v.redd.it/9bo4r6mgjej31/HLSPlaylist.m3u8",
      is_gif: false,
      transcoding_status: "completed",
    },
  },
  is_reddit_media_domain: true,
  is_meta: false,
  category: null,
  secure_media_embed: {},
  link_flair_text: null,
  can_mod_post: false,
  score: 27232,
  approved_by: null,
  thumbnail:
    "https://a.thumbs.redditmedia.com/WUKFfxrAsCTDG1GQL17cxWTbbluXUI_aTikdzZ2gUd0.jpg",
  edited: false,
  author_flair_css_class: null,
  author_flair_richtext: [],
  gildings: {},
  post_hint: "hosted:video",
  content_categories: null,
  is_self: false,
  mod_note: null,
  created: 1567119422,
  link_flair_type: "text",
  wls: 6,
  banned_by: null,
  author_flair_type: "text",
  domain: "v.redd.it",
  allow_live_comments: true,
  selftext_html: null,
  likes: null,
  suggested_sort: null,
  banned_at_utc: null,
  view_count: null,
  archived: false,
  no_follow: false,
  is_crosspostable: false,
  pinned: false,
  over_18: false,
  preview: {
    images: [
      {
        source: {
          url:
            "https://external-preview.redd.it/eTqqquNUuutI0tsm9Y7neAeBIl222f8BDrXloAB_DTk.png?format=pjpg&auto=webp&s=b8192312ebfa22f93d97efee1fec2ab8eb9db606",
          width: 270,
          height: 480,
        },
        resolutions: [
          {
            url:
              "https://external-preview.redd.it/eTqqquNUuutI0tsm9Y7neAeBIl222f8BDrXloAB_DTk.png?width=108&crop=smart&format=pjpg&auto=webp&s=09764e5b2812a8e6c9facaef1861336d63d5001c",
            width: 108,
            height: 192,
          },
          {
            url:
              "https://external-preview.redd.it/eTqqquNUuutI0tsm9Y7neAeBIl222f8BDrXloAB_DTk.png?width=216&crop=smart&format=pjpg&auto=webp&s=c65cfc2ae855b8606a4cd2aa763fa12c873b2829",
            width: 216,
            height: 384,
          },
        ],
        variants: {},
        id: "xF_JzeFO5QFcM7sDCdSxg9wYdaE8865IpjqtIThQCcg",
      },
    ],
    enabled: false,
  },
  all_awardings: [],
  media_only: false,
  can_gild: false,
  spoiler: false,
  locked: false,
  author_flair_text: null,
  visited: false,
  num_reports: null,
  distinguished: null,
  subreddit_id: "t5_3h4zq",
  mod_reason_by: null,
  removal_reason: null,
  link_flair_background_color: "",
  id: "cx20x5",
  is_robot_indexable: true,
  report_reasons: null,
  author: { name: "BreakingThoseCankles" },
  num_crossposts: 12,
  num_comments: 1392,
  send_replies: true,
  whitelist_status: "all_ads",
  contest_mode: false,
  mod_reports: [],
  author_patreon_flair: false,
  author_flair_text_color: null,
  permalink:
    "/r/WatchPeopleDieInside/comments/cx20x5/therea_a_girl_in_this_party_shocked_by_this_dudes/",
  parent_whitelist_status: "all_ads",
  stickied: false,
  url: "https://v.redd.it/9bo4r6mgjej31",
  subreddit_subscribers: 1326661,
  created_utc: 1567090622,
  discussion_type: null,
  media: {
    reddit_video: {
      fallback_url: "https://v.redd.it/9bo4r6mgjej31/DASH_480?source=fallback",
      height: 480,
      width: 270,
      scrubber_media_url: "https://v.redd.it/9bo4r6mgjej31/DASH_96",
      dash_url: "https://v.redd.it/9bo4r6mgjej31/DASHPlaylist.mpd",
      duration: 19,
      hls_url: "https://v.redd.it/9bo4r6mgjej31/HLSPlaylist.m3u8",
      is_gif: false,
      transcoding_status: "completed",
    },
  },
  is_video: true,
  comments: [],
};

export default { videoAudio, videoNoAudio, videoIsGif, tweet };
